def print_A():
    print("    A    ")
    print("   / \   ")
    print("  /___\  ")
    print(" /     \ ")
    print("/       \\")
def print_I():
    print("_________")
    print("    |    ")
    print("    |    ")
    print("    |    ")
    print("____|____")
def print_M():
    print("|\     /|")
    print("| \   / |")
    print("|  \ /  |")
    print("|   V   |")
    print("|       |")
def print_O():
    print("  _____  ")
    print(" /     \ ")
    print(" |     | ")
    print(" |     | ")
    print(" \_____/ ")
def print_R():
    print("  ____  ")
    print("  |   \ ")
    print("  |___/  ")
    print("  | \   ")
    print("  |  \  ")
    print("  |   \  ")
print_M()
print()
print_A()
print()
print_R()
print()
print_I()
print()
print_O()
print()
name = input("")